# Generated by Django 3.2.2 on 2021-05-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narx', models.FloatField()),
                ('tarif', models.TextField(null=True)),
                ('soni', models.IntegerField(default=10)),
                ('toifasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopp.toifa')),
            ],
        ),
    ]
